In [1]:
#Course information: CSE 5544 data visualization midterm project
#Author: Su, Ming Yi
#Date: 11/05/2018
#Note: The whole lab is tested with Python 3.6
#Data source: data.csv
# coding = utf-8
# Goal create another table
# DEP ARR total_flight AIR_TIME DISTANCE Pr(DEP) Avg_DEP_TIME Pr(ARR) Avg_ARR_TIME

In [2]:
# import necessary packages used in this project
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
# Create a pandas DataFrame from the file
df = pd.read_csv("data.csv");
#data
print(df.head())

   DAY_OF_MONTH  DAY_OF_WEEK ORIGIN ORIGIN_CITY_NAME ORIGIN_STATE_ABR DEST  \
0             1            7    ATL      Atlanta, GA               GA  GTR
1             1            7    GTR     Columbus, MS               MS  ATL
2             1            7    ATL      Atlanta, GA               GA  GTR
3             1            7    GTR     Columbus, MS               MS  ATL
4             1            7    ATL      Atlanta, GA               GA  FAY

     DEST_CITY_NAME DEST_STATE_ABR  DEP_DELAY_NEW  DEP_DEL15  ARR_DELAY_NEW  \
0      Columbus, MS             MS            0.0        0.0            0.0
1       Atlanta, GA             GA            0.0        0.0            0.0
2      Columbus, MS             MS            0.0        0.0            0.0
3       Atlanta, GA             GA            0.0        0.0            0.0
4  Fayetteville, NC             NC            0.0        0.0            0.0

   ARR_DEL15  AIR_TIME  DISTANCE  CARRIER_DELAY  WEATHER_DELAY  NAS_DELAY  \
0        0.0      43.0     241.0            NaN            NaN        NaN
1        0.0      47.0     241.0            NaN            NaN        NaN
2        0.0      42.0     241.0            NaN            NaN        NaN
3        0.0      46.0     241.0            NaN            NaN        NaN
4        0.0      49.0     331.0            NaN            NaN        NaN

   SECURITY_DELAY  LATE_AIRCRAFT_DELAY  Unnamed: 19
0             NaN                  NaN          NaN
1             NaN                  NaN          NaN
2             NaN                  NaN          NaN
3             NaN                  NaN          NaN
4             NaN                  NaN          NaN

In [74]:
# summary table for all flights
summary = df.groupby(["ORIGIN", "DEST"]).size().reset_index(name='total_flights');
#print(summary);
#print(len(summary.index));
# There are 5842 kinds of flights in our data
DEP = summary.iloc[0,0];
ARR = summary.iloc[0,1];
total_flight = summary.iloc[0,2];
sub_data = df[(df['ORIGIN']==DEP)&(df['DEST']==ARR)];

AIR_TIME = sub_data['AIR_TIME'].sum()/total_flight;
DISTANCE = sub_data['DISTANCE'].sum()/total_flight;

DEP_delay_times = sub_data['DEP_DEL15'].sum();
DEP_Pr = DEP_delay_times/total_flight;
DEP_delay_time = sub_data['DEP_DELAY_NEW'].sum()/DEP_delay_times;

ARR_delay_times = sub_data['ARR_DEL15'].sum();
ARR_Pr = ARR_delay_times/total_flight;
ARR_delay_time = sub_data['ARR_DELAY_NEW'].sum()/ARR_delay_times;

print("DEP: ",DEP);
print("ARR: ",ARR);
print("total_flight: ", total_flight);
print("AIR_TIME: ",AIR_TIME);
print("DISTANCE: ",DISTANCE);
print("DEP_delay_times: ",DEP_delay_times);
print("DEP_Pr: ",DEP_Pr);
print("DEP_delay_time: ",DEP_delay_time);
print("ARR_delay_times: ",ARR_delay_times);
print("ARR_Pr: ",ARR_Pr);
print("ARR_delay_time: ",ARR_delay_time);

DEP = [];
ARR = [];
total_flight = [];
AIR_TIME = [];
DISTANCE = [];
DEP_delay_times = [];
DEP_Pr = [];
DEP_delay_time = [];
ARR_delay_times =[];
ARR_Pr = [];
ARR_delay_time = [];
#for i in range(0, 10):
for i in range(0, len(summary.index)):
    tmp_DEP = summary.iloc[i,0];
    tmp_ARR = summary.iloc[i,1];
    tmp_total_flight = summary.iloc[i,2];

    sub_data = df[(df['ORIGIN']==tmp_DEP)&(df['DEST']==tmp_ARR)];
    
    tmp_AIR_TIME = sub_data['AIR_TIME'].sum()/tmp_total_flight;
    tmp_DISTANCE = sub_data['DISTANCE'].sum()/tmp_total_flight;

    tmp_DEP_delay_time =0;
    tmp_ARR_delay_time =0;
    
    tmp_DEP_delay_times = sub_data['DEP_DEL15'].sum();
    tmp_DEP_Pr = tmp_DEP_delay_times/tmp_total_flight;
    if(tmp_DEP_delay_times>0):
        tmp_DEP_delay_time = sub_data['DEP_DELAY_NEW'].sum()/tmp_DEP_delay_times;
    if(tmp_DEP_delay_times==0):
        tmp_DEP_delay_time =0;
    tmp_ARR_delay_times = sub_data['ARR_DEL15'].sum();
    tmp_ARR_Pr = tmp_ARR_delay_times/tmp_total_flight;
    if(tmp_ARR_delay_times>0):
        tmp_ARR_delay_time = sub_data['ARR_DELAY_NEW'].sum()/tmp_ARR_delay_times;
    if(tmp_ARR_delay_times==0):
        tmp_ARR_delay_time =0;
    DEP.append(tmp_DEP);
    ARR.append(tmp_ARR);
    total_flight.append(tmp_total_flight);
    AIR_TIME.append(tmp_AIR_TIME);
    DISTANCE.append(tmp_DISTANCE);
    DEP_delay_times.append(tmp_DEP_delay_times);
    DEP_Pr.append(tmp_DEP_Pr);
    DEP_delay_time.append(tmp_DEP_delay_time);
    ARR_delay_times.append(tmp_ARR_delay_times);
    ARR_Pr.append(tmp_ARR_Pr);
    ARR_delay_time.append(tmp_ARR_delay_time);


dict = {
    "DEP":DEP,
    "ARR":ARR,
    "total_flight":total_flight,
    "AIR_TIME":AIR_TIME,
    "DISTANCE":DISTANCE,
    "DEP_delay_times":DEP_delay_times,
    "DEP_Pr":DEP_Pr,
    "DEP_delay_time":DEP_delay_time,
    "ARR_delay_times":ARR_delay_times,
    "ARR_PR":ARR_Pr,
    "ARR_delay_time":ARR_delay_time
}
final_df = pd.DataFrame(dict)    
print(final_df.head());
final_df.to_csv("summary_table.csv", index=False)
print(len(summary.index));
print(df.groupby(["ORIGIN"]).size());

DEP:  ABE
ARR:  ATL
total_flight:  83
AIR_TIME:  99.01204819277109
DISTANCE:  692.0
DEP_delay_times:  6.0
DEP_Pr:  0.07228915662650602
DEP_delay_time:  251.5
ARR_delay_times:  11.0
ARR_Pr:  0.13253012048192772
ARR_delay_time:  163.45454545454547
     AIR_TIME  ARR    ARR_PR  ARR_delay_time  ARR_delay_times  DEP    DEP_Pr  \
0   99.012048  ATL  0.132530      163.454545             11.0  ABE  0.072289
1   88.459770  CLT  0.195402       76.764706             17.0  ABE  0.195402
2   74.042254  DTW  0.154930       90.636364             11.0  ABE  0.169014
3  125.000000  FLL  0.700000       71.142857              7.0  ABE  0.700000
4   75.235294  MYR  0.058824       72.000000              1.0  ABE  0.000000

   DEP_delay_time  DEP_delay_times  DISTANCE  total_flight
0      251.500000              6.0     692.0            83
1       87.411765             17.0     481.0            87
2       94.500000             12.0     425.0            71
3       69.857143              7.0    1041.0            10
4        0.000000              0.0     518.0            17

In [12]:
# get the summary table for date
date_df = df.groupby(["DAY_OF_MONTH", "DEP_DEL15", "ARR_DEL15"]).size().reset_index(name='total_flight');
#print(date_df);
date_df.to_csv("date_table.csv", index=False)

week_df = df.groupby(["DAY_OF_WEEK","DEP_DEL15", "ARR_DEL15"]).size().reset_index(name='total_flight');
#print(week_df);
week_df.to_csv("week_table.csv", index=False)

#delay_df = df.groupby(["DEP_DEL15", "ARR_DEL15"]).size().reset_index(name='delay_relation');
#print(delay_df);

,DAY_OF_MONTH,DAY_OF_WEEK,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEP_DELAY_NEW,DEP_DEL15,ARR_DELAY_NEW,ARR_DEL15,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 19
0,1,7,ATL,"Atlanta, GA",GA,GTR,"Columbus, MS",MS,0.0,0.0,0.0,0.0,43.0,241.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,7,GTR,"Columbus, MS",MS,ATL,"Atlanta, GA",GA,0.0,0.0,0.0,0.0,47.0,241.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1,7,ATL,"Atlanta, GA",GA,GTR,"Columbus, MS",MS,0.0,0.0,0.0,0.0,42.0,241.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1,7,GTR,"Columbus, MS",MS,ATL,"Atlanta, GA",GA,0.0,0.0,0.0,0.0,46.0,241.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1,7,ATL,"Atlanta, GA",GA,FAY,"Fayetteville, NC",NC,0.0,0.0,0.0,0.0,49.0,331.0,NaN,NaN,NaN,NaN,NaN,NaN
5,1,7,FAY,"Fayetteville, NC",NC,ATL,"Atlanta, GA",GA,0.0,0.0,0.0,0.0,62.0,331.0,NaN,NaN,NaN,NaN,NaN,NaN
6,1,7,ATL,"Atlanta, GA",GA,TLH,"Tallahassee, FL",FL,0.0,0.0,0.0,0.0,39.0,223.0,NaN,NaN,NaN,NaN,NaN,NaN
7,1,7,TLH,"Tallahassee, FL",FL,ATL,"Atlanta, GA",GA,0.0,0.0,NaN,NaN,44.0,223.0,NaN,NaN,NaN,NaN,NaN,NaN
8,1,7,LGA,"New York, NY",NY,BTV,"Burlington, VT",VT,0.0,0.0,0.0,0.0,47.0,258.0,NaN,NaN,NaN,NaN,NaN,NaN
9,1,7,ATL,"Atlanta, GA",GA,TRI,"Bristol/Johnson City/Kingsport, TN",TN,0.0,0.0,0.0,0.0,38.0,227.0,NaN,NaN,NaN,NaN,NaN,NaN
10,1,7,TRI,"Bristol/Johnson City/Kingsport, TN",TN,ATL,"Atlanta, GA",GA,0.0,0.0,0.0,0.0,45.0,227.0,NaN,NaN,NaN,NaN,NaN,NaN
11,1,7,RDU,"Raleigh/Durham, NC",NC,JFK,"New York, NY",NY,9.0,0.0,0.0,0.0,63.0,427.0,NaN,NaN,NaN,NaN,NaN,NaN
12,1,7,LGA,"New York, NY",NY,BTV,"Burlington, VT",VT,0.0,0.0,0.0,0.0,46.0,258.0,NaN,NaN,NaN,NaN,NaN,NaN
13,1,7,BTR,"Baton Rouge, LA",LA,ATL,"Atlanta, GA",GA,0.0,0.0,0.0,0.0,68.0,448.0,NaN,NaN,NaN,NaN,NaN,NaN
14,1,7,MSP,"Minneapolis, MN",MN,DSM,"Des Moines, IA",IA,0.0,0.0,0.0,0.0,38.0,232.0,NaN,NaN,NaN,NaN,NaN,NaN
15,1,7,LNK,"Lincoln, NE",NE,ATL,"Atlanta, GA",GA,0.0,0.0,0.0,0.0,115.0,841.0,NaN,NaN,NaN,NaN,NaN,NaN
16,1,7,OMA,"Omaha, NE",NE,DTW,"Detroit, MI",MI,0.0,0.0,0.0,0.0,86.0,651.0,NaN,NaN,NaN,NaN,NaN,NaN
17,1,7,BTV,"Burlington, VT",VT,DTW,"Detroit, MI",MI,0.0,0.0,0.0,0.0,81.0,537.0,NaN,NaN,NaN,NaN,NaN,NaN
18,1,7,DTW,"Detroit, MI",MI,IAD,"Washington, DC",VA,NaN,NaN,0.0,0.0,59.0,383.0,NaN,NaN,NaN,NaN,NaN,NaN
19,1,7,IAD,"Washington, DC",VA,DTW,"Detroit, MI",MI,NaN,NaN,0.0,0.0,59.0,383.0,NaN,NaN,NaN,NaN,NaN,NaN
20,1,7,BNA,"Nashville, TN",TN,JFK,"New York, NY",NY,0.0,0.0,0.0,0.0,110.0,765.0,NaN,NaN,NaN,NaN,NaN,NaN
21,1,7,LGA,"New York, NY",NY,PWM,"Portland, ME",ME,0.0,0.0,0.0,0.0,44.0,269.0,NaN,NaN,NaN,NaN,NaN,NaN
22,1,7,CVG,"Cincinnati, OH",KY,DCA,"Washington, DC",VA,0.0,0.0,0.0,0.0,59.0,411.0,NaN,NaN,NaN,NaN,NaN,NaN
23,1,7,BOS,"Boston, MA",MA,CVG,"Cincinnati, OH",KY,0.0,0.0,0.0,0.0,97.0,752.0,NaN,NaN,NaN,NaN,NaN,NaN
24,1,7,MSP,"Minneapolis, MN",MN,TYS,"Knoxville, TN",TN,33.0,1.0,33.0,1.0,106.0,792.0,33.0,0.0,0.0,0.0,0.0,NaN
25,1,7,ATL,"Atlanta, GA",GA,GNV,"Gainesville, FL",FL,0.0,0.0,18.0,1.0,51.0,300.0,0.0,0.0,18.0,0.0,0.0,NaN
26,1,7,ATL,"Atlanta, GA",GA,CRW,"Charleston/Dunbar, WV",WV,3.0,0.0,0.0,0.0,64.0,363.0,NaN,NaN,NaN,NaN,NaN,NaN
27,1,7,CRW,"Charleston/Dunbar, WV",WV,ATL,"Atlanta, GA",GA,NaN,NaN,0.0,0.0,58.0,363.0,NaN,NaN,NaN,NaN,NaN,NaN
28,1,7,AGS,"Augusta, GA",GA,ATL,"Atlanta, GA",GA,0.0,0.0,0.0,0.0,33.0,143.0,NaN,NaN,NaN,NaN,NaN,NaN
29,1,7,LGA,"New York, NY",NY,BUF,"Buffalo, NY",NY,0.0,0.0,0.0,0.0,48.0,292.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701844,31,2,CIU,"Sault Ste. Marie, MI",MI,DTW,"Detroit, MI",MI,0.0,0.0,20.0,1.0,53.0,284.0,0.0,0.0,20.0,0.0,0.0,NaN
701845,31,2,DTW,"Detroit, MI",MI,CIU,"Sault Ste. Marie, MI",MI,0.0,0.0,0.0,0.0,46.0,284.0,NaN,NaN,NaN,NaN,NaN,NaN
701846,31,2,DTW,"Detroit, MI",MI,PLN,"Pellston, MI",MI,0.0,0.0,0.0,0.0,40.0,243.0,NaN,NaN,NaN,NaN,NaN,NaN
701847,31,2,PLN,"Pellston, MI",MI,DTW,"Detroit, MI",MI,0.0,0.0,0.0,0.0,51.0,243.0,NaN,NaN,NaN,NaN,NaN,NaN
701848,31,2,SLC,"Salt Lake City, UT",UT,GTF,"Great Falls, MT",MT,0.0,0.0,0.0,0.0,67.0,463.0,NaN,NaN,NaN,NaN,NaN,NaN
701849,31,2,LWS,"Lewiston, ID",ID,SLC,"Salt Lake City, UT",UT,0.0,0.0,0.0,0.0,62.0,461.0,NaN,NaN,NaN,NaN,NaN,NaN
701850,31,2,RHI,"Rhinelander, WI",WI,MSP,"Minneapolis, MN",MN,0.0,0.0,0.0,0.0,38.0,190.0,NaN,NaN,NaN,NaN,NaN,NaN
701851,31,2,MSP,"Minneapolis, MN",MN,RHI,"Rhinelander, WI",WI,0.0,0.0,0.0,0.0,32.0,190.0,NaN,NaN,NaN,NaN,NaN,NaN
701852,31,2,MSP,"Minneapolis, MN",MN,RHI,"Rhinelander, WI",WI,0.0,0.0,0.0,0.0,33.0,190.0,NaN,NaN,NaN,NaN,NaN,NaN
701853,31,2,RHI,"Rhinelander, WI",WI,MSP,"Minneapolis, MN",MN,0.0,0.0,0.0,0.0,39.0,190.0,NaN,NaN,NaN,NaN,NaN,NaN
701854,31,2,MSP,"Minneapolis, MN",MN,ABR,"Aberdeen, SD",SD,0.0,0.0,0.0,0.0,41.0,257.0,NaN,NaN,NaN,NaN,NaN,NaN
701855,31,2,DTW,"Detroit, MI",MI,BGM,"Binghamton, NY",NY,0.0,0.0,2.0,0.0,54.0,378.0,NaN,NaN,NaN,NaN,NaN,NaN
701856,31,2,ITH,"Ithaca/Cortland, NY",NY,DTW,"Detroit, MI",MI,0.0,0.0,0.0,0.0,57.0,353.0,NaN,NaN,NaN,NaN,NaN,NaN
701857,31,2,LSE,"La Crosse, WI",WI,MSP,"Minneapolis, MN",MN,0.0,0.0,0.0,0.0,26.0,119.0,NaN,NaN,NaN,NaN,NaN,NaN
701858,31,2,BRD,"Brainerd, MN",MN,MSP,"Minneapolis, MN",MN,0.0,0.0,12.0,0.0,27.0,114.0,NaN,NaN,NaN,NaN,NaN,NaN
701859,31,2,INL,"International Falls, MN",MN,MSP,"Minneapolis, MN",MN,0.0,0.0,0.0,0.0,45.0,255.0,NaN,NaN,NaN,NaN,NaN,NaN
701860,31,2,MSP,"Minneapolis, MN",MN,INL,"International Falls, MN",MN,0.0,0.0,0.0,0.0,47.0,255.0,NaN,NaN,NaN,NaN,NaN,NaN
701861,31,2,DTW,"Detroit, MI",MI,ITH,"Ithaca/Cortland, NY",NY,0.0,0.0,0.0,0.0,50.0,353.0,NaN,NaN,NaN,NaN,NaN,NaN
701862,31,2,ITH,"Ithaca/Cortland, NY",NY,DTW,"Detroit, MI",MI,0.0,0.0,0.0,0.0,66.0,353.0,NaN,NaN,NaN,NaN,NaN,NaN
701863,31,2,PIH,"Pocatello, ID",ID,SLC,"Salt Lake City, UT",UT,0.0,0.0,0.0,0.0,36.0,150.0,NaN,NaN,NaN,NaN,NaN,NaN
701864,31,2,SLC,"Salt Lake City, UT",UT,PIH,"Pocatello, ID",ID,0.0,0.0,0.0,0.0,29.0,150.0,NaN,NaN,NaN,NaN,NaN,NaN
701865,31,2,SLC,"Salt Lake City, UT",UT,LWS,"Lewiston, ID",ID,0.0,0.0,0.0,0.0,66.0,461.0,NaN,NaN,NaN,NaN,NaN,NaN
701866,31,2,SLC,"Salt Lake City, UT",UT,TWF,"Twin Falls, ID",ID,1.0,0.0,18.0,1.0,33.0,175.0,1.0,0.0,17.0,0.0,0.0,NaN
701867,31,2,TWF,"Twin Falls, ID",ID,SLC,"Salt Lake City, UT",UT,11.0,0.0,15.0,1.0,34.0,175.0,0.0,0.0,4.0,0.0,11.0,NaN
701868,31,2,DTW,"Detroit, MI",MI,ITH,"Ithaca/Cortland, NY",NY,3.0,0.0,4.0,0.0,50.0,353.0,NaN,NaN,NaN,NaN,NaN,NaN
701869,31,2,BGM,"Binghamton, NY",NY,DTW,"Detroit, MI",MI,0.0,0.0,0.0,0.0,65.0,378.0,NaN,NaN,NaN,NaN,NaN,NaN
701870,31,2,DTW,"Detroit, MI",MI,BGM,"Binghamton, NY",NY,0.0,0.0,0.0,0.0,55.0,378.0,NaN,NaN,NaN,NaN,NaN,NaN
701871,31,2,MSP,"Minneapolis, MN",MN,IMT,"Iron Mountain/Kingsfd, MI",MI,0.0,0.0,0.0,0.0,46.0,257.0,NaN,NaN,NaN,NaN,NaN,NaN
701872,31,2,INL,"International Falls, MN",MN,MSP,"Minneapolis, MN",MN,0.0,0.0,0.0,0.0,49.0,255.0,NaN,NaN,NaN,NaN,NaN,NaN
701873,31,2,MSP,"Minneapolis, MN",MN,INL,"International Falls, MN",MN,4.0,0.0,0.0,0.0,41.0,255.0,NaN,NaN,NaN,NaN,NaN,NaN